### ISSUE TITLE
Development packages being included

### ISSUE THREAD

**Issue by thompson-tomo** [me-viper/OpaDotNet#33]
**Describe the bug**
Currently the package has dependencies on

- [JetBrains.Annotations](https://www.nuget.org/packages/JetBrains.Annotations/)
- [Semver](https://www.nuget.org/packages/Semver/)

**Expected behavior**
Those packages should not be included as a dependency as they are development time and hence should be defined as private assets.

**Version all**

**Comment by me-viper** [comment]
Semver is not development dependency. It's used to support [semver](https://www.openpolicyagent.org/docs/latest/policy-reference/#semver) built-ins.
